import type { CertificateTemplate } from '../types/certificate';

export const TEMPLATES: CertificateTemplate[] = [
  {
    id: 'rising-yoga-official',
    name: 'Rising Yoga (Official)',
    subtitle: 'Official Face Yoga Certificate with gold rosette & emblem',
    badge: 'Default Official',
    recommendedFontId: 'magnolia',
    backgroundUri: '/rising-yoga-default.png',
    viewBox: {
      width: 1414,
      height: 1000,
    },
    defaultValues: {
      recipientName: 'Neha Varma',
      date: 'September 24, 2026',
      courseName: 'NA',
      instructorName: 'NA',
      certificateId: 'NA',
    },
    fields: {
      recipientName: {
        x: 707, // centered
        y: 462, // centered in the blank recipient area between "THIS CERTIFIES THAT" and "has demonstrated..."
        maxWidth: 960,
        defaultFontSize: 64,
        minFontSize: 30,
        color: '#23180c',
        alignment: 'middle',
        fontWeight: 'normal',
      },
      date: {
        x: 489, // exact center of the horizontal date line on the left
        y: 820, // positioned right above the horizontal date line (line at Y=832)
        maxWidth: 240,
        defaultFontSize: 16,
        minFontSize: 12,
        color: '#261c10',
        alignment: 'middle',
      },
    },
  },
  {
    id: 'modern-gold',
    name: 'Modern Executive Gold',
    subtitle: 'Sleek dark navy & gold luxury border for workshops and coaching',
    badge: 'Modern',
    recommendedFontId: 'higuen',
    viewBox: {
      width: 1414,
      height: 1000,
    },
    defaultValues: {
      recipientName: 'Neha Varma',
      courseName: 'NA',
      date: 'September 24, 2026',
      instructorName: 'NA',
      certificateId: 'NA',
    },
    fields: {
      recipientName: {
        x: 707,
        y: 520,
        maxWidth: 900,
        defaultFontSize: 62,
        minFontSize: 28,
        color: '#0f172a',
        alignment: 'middle',
        fontWeight: 'normal',
      },
      courseName: {
        x: 707,
        y: 675,
        maxWidth: 820,
        defaultFontSize: 24,
        minFontSize: 18,
        color: '#b45309',
        alignment: 'middle',
        letterSpacing: '0.12em',
        textTransform: 'uppercase',
      },
      date: {
        x: 330,
        y: 860,
        maxWidth: 250,
        defaultFontSize: 18,
        minFontSize: 14,
        color: '#334155',
        alignment: 'middle',
      },
      instructorName: {
        x: 1084,
        y: 860,
        maxWidth: 250,
        defaultFontSize: 18,
        minFontSize: 14,
        color: '#334155',
        alignment: 'middle',
      },
      certificateId: {
        x: 707,
        y: 948,
        maxWidth: 400,
        defaultFontSize: 12,
        minFontSize: 10,
        color: '#94a3b8',
        alignment: 'middle',
        letterSpacing: '0.15em',
      },
    },
  },
  {
    id: 'classical-academy',
    name: 'Classical Academy Diploma',
    subtitle: 'Traditional parchment with filigree borders and seal',
    badge: 'Classic',
    recommendedFontId: 'cormorant',
    viewBox: {
      width: 1414,
      height: 1000,
    },
    defaultValues: {
      recipientName: 'Neha Varma',
      courseName: 'NA',
      date: 'September 24, 2026',
      instructorName: 'NA',
      certificateId: 'NA',
    },
    fields: {
      recipientName: {
        x: 707,
        y: 530,
        maxWidth: 880,
        defaultFontSize: 60,
        minFontSize: 28,
        color: '#18181b',
        alignment: 'middle',
      },
      courseName: {
        x: 707,
        y: 680,
        maxWidth: 820,
        defaultFontSize: 24,
        minFontSize: 18,
        color: '#78350f',
        alignment: 'middle',
        letterSpacing: '0.1em',
        textTransform: 'uppercase',
      },
      date: {
        x: 340,
        y: 860,
        maxWidth: 240,
        defaultFontSize: 17,
        minFontSize: 14,
        color: '#3f3f46',
        alignment: 'middle',
      },
      instructorName: {
        x: 1074,
        y: 860,
        maxWidth: 240,
        defaultFontSize: 17,
        minFontSize: 14,
        color: '#3f3f46',
        alignment: 'middle',
      },
      certificateId: {
        x: 707,
        y: 945,
        maxWidth: 400,
        defaultFontSize: 12,
        minFontSize: 10,
        color: '#a1a1aa',
        alignment: 'middle',
        letterSpacing: '0.15em',
      },
    },
  },
];
